### ISSUE TITLE
 Offtopic

### ISSUE THREAD

**Issue by pomazanbohdan** [Elastictable/cdk#13]
Hey.
Do you think using one table is good for building a CRM system?

**Comment by stephankaag** [comment]
> Hey.
> Do you think using one table is good for building a CRM system?

As long as you know your access patterns in advance, it is.

Did you read https://www.alexdebrie.com/posts/dynamodb-single-table/?

**Comment by pomazanbohdan** [comment]
I read different articles and I got the main idea.
It's just that I have a complex architecture in my head, and I'm not sure that it will fall on one table in terms of performance.
